const getUrl = (name: string) => new URL(`./${name}.webp`, import.meta.url).href

export const bannerDesktop = getUrl('banner-desktop')
export const bannerMobile = getUrl('banner-mobile')
export const beyondBasicControls = getUrl('beyond-basic-controls')
export const carPlayAndAndroidAuto = getUrl('car-play-and-android-auto')
export const connectConsoles = getUrl('connect-consoles')
export const dualViewMode = getUrl('dual-view-mode')
export const gamingDesktop = getUrl('gaming-desktop')
export const gamingMobile = getUrl('gaming-mobile')
export const navigationDesktop = getUrl('navigation-desktop')
export const navigationMobile = getUrl('navigation-mobile')
export const socialDesktop = getUrl('social-desktop')
export const socialMobile = getUrl('social-mobile')
export const streamingDesktop = getUrl('streaming-desktop')
export const streamingMobile = getUrl('streaming-mobile')
