const getUrl = (name: string) => new URL(`./${name}.webp`, import.meta.url).href

export const bannerDesktop = getUrl('banner-desktop')
export const bannerMobile = getUrl('banner-mobile')
export const beyondBasicControlsDesktop = getUrl('beyond-basic-controls-desktop')
export const beyondBasicControlsMobile = getUrl('beyond-basic-controls-mobile')
export const carPlayAndAndroidAutoDesktop = getUrl('car-play-and-android-auto-desktop')
export const carPlayAndAndroidAutoMobile = getUrl('car-play-and-android-auto-mobile')
export const connectConsolesDesktop = getUrl('connect-consoles-desktop')
export const connectConsolesMobile = getUrl('connect-consoles-mobile')
export const dualViewModeDesktop = getUrl('dual-view-mode-desktop')
export const dualViewModeMobile = getUrl('dual-view-mode-mobile')
export const gamingDesktop = getUrl('gaming-desktop')
export const gamingMobile = getUrl('gaming-mobile')
export const navigationDesktop = getUrl('navigation-desktop')
export const navigationMobile = getUrl('navigation-mobile')
export const socialDesktop = getUrl('social-desktop')
export const socialMobile = getUrl('social-mobile')
export const streamingDesktop = getUrl('streaming-desktop')
export const streamingMobile = getUrl('streaming-mobile')
